apiVersion: v1 
kind: Service
metadata:
  name: srv-demo
  labels:
    app: petclinic:1.0.0
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000